### ISSUE TITLE
Output color hardcoded?

### ISSUE THREAD

**Issue by 097115** [robin-mbg/may#4]
Seems that `may`'s output color is hardcoded to white, isn't it? On white terminals you don't see much :)

**Comment by robin-mbg** [comment]
Thanks a lot for reporting this issue, this seems quite severe given the market share of light color schemes. I have hopefully addressed this in `v1.1.1` by not specifying any color for default output and dynamically using the terminal theme's colors when additional output is generated with increased verbosity (`-v`). 

If you experience any further issues with output visibility, do not hesitate to extend upon this issue. For now, I'll regard this as closed.

**Comment by 097115** [comment]
Well, it seems to work nice on macOS (tested in iTerm and Alacritty) but fails on Ubuntu 16.04 (tested in LXTerminal and [ROXTerm](https://github.com/realh/roxterm)).

**Comment by robin-mbg** [comment]
Just tested it in LXTerminal and ROXTerm on Arch and that seems to work fine and I don't have a Ubuntu ready to play with at the moment to replicate that issue. It seems like the color library that `may` uses has had [some bugfixes](https://github.com/gookit/color/releases) in this direction over the past months and maybe the upgrade from `1.2.3` to `1.3.0` helps fix that issue.

**Comment by 097115** [comment]
> maybe the upgrade from 1.2.3 to 1.3.0 helps fix that issue

Nope, still same story for me. Probably, something strange on my side, don't you worry / bother :)

Thanks for the support.
